[package]
name = "kura"
version = "0.1.8"
edition = "2021"

[dependencies]
crossterm = "0.26"
ratatui = { version = "0.20", features = ["crossterm"] }
image = "0.23"
viuer = "0.4"
unicode-width = "0.1"
